name: "Install dependencies"
description: "Prepare the repository and all dependencies"

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7.28.0

    - name: Set up node
      uses: actions/setup-node@v3
      with:
        cache: pnpm
        node-version: 18

    - name: Install dependencies
      shell: bash
      run: pnpm install
