// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts"
// @generated from file substreams/proxy/v1/proxy.proto (package substreams.proxy.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ProxyRequest } from "./proxy_pb.js";
import { Response } from "@substreams/core/proto/sf/substreams/rpc/v2/service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service substreams.proxy.v1.ProxyService
 */
export const ProxyService = {
  typeName: "substreams.proxy.v1.ProxyService",
  methods: {
    /**
     * @generated from rpc substreams.proxy.v1.ProxyService.Proxy
     */
    proxy: {
      name: "Proxy",
      I: ProxyRequest,
      O: Response,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

