// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file sf/substreams/sink/service/v1/service.proto (package sf.substreams.sink.service.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeployRequest, DeployResponse, InfoRequest, InfoResponse, ListRequest, ListResponse, PauseRequest, PauseResponse, RemoveRequest, RemoveResponse, ResumeRequest, ResumeResponse, StopRequest, StopResponse, UpdateRequest, UpdateResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service sf.substreams.sink.service.v1.Provider
 */
export const Provider = {
  typeName: "sf.substreams.sink.service.v1.Provider",
  methods: {
    /**
     * @generated from rpc sf.substreams.sink.service.v1.Provider.Deploy
     */
    deploy: {
      name: "Deploy",
      I: DeployRequest,
      O: DeployResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sf.substreams.sink.service.v1.Provider.Update
     */
    update: {
      name: "Update",
      I: UpdateRequest,
      O: UpdateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sf.substreams.sink.service.v1.Provider.Info
     */
    info: {
      name: "Info",
      I: InfoRequest,
      O: InfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sf.substreams.sink.service.v1.Provider.List
     */
    list: {
      name: "List",
      I: ListRequest,
      O: ListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sf.substreams.sink.service.v1.Provider.Pause
     */
    pause: {
      name: "Pause",
      I: PauseRequest,
      O: PauseResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sf.substreams.sink.service.v1.Provider.Stop
     */
    stop: {
      name: "Stop",
      I: StopRequest,
      O: StopResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sf.substreams.sink.service.v1.Provider.Resume
     */
    resume: {
      name: "Resume",
      I: ResumeRequest,
      O: ResumeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sf.substreams.sink.service.v1.Provider.Remove
     */
    remove: {
      name: "Remove",
      I: RemoveRequest,
      O: RemoveResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

