// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=.js"
// @generated from file sf/substreams/rpc/v3/service.proto (package sf.substreams.rpc.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_any } from "@bufbuild/protobuf/wkt";
import { file_sf_firehose_v2_firehose } from "../../../firehose/v2/firehose_pb.js";
import type { ResponseSchema } from "../v2/service_pb.js";
import { file_sf_substreams_rpc_v2_service } from "../v2/service_pb.js";
import { file_sf_substreams_v1_clock } from "../../v1/clock_pb.js";
import { file_sf_substreams_v1_modules } from "../../v1/modules_pb.js";
import type { Package } from "../../v1/package_pb.js";
import { file_sf_substreams_v1_package } from "../../v1/package_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sf/substreams/rpc/v3/service.proto.
 */
export const file_sf_substreams_rpc_v3_service: GenFile = /*@__PURE__*/
  fileDesc("CiJzZi9zdWJzdHJlYW1zL3JwYy92My9zZXJ2aWNlLnByb3RvEhRzZi5zdWJzdHJlYW1zLnJwYy52MyKIBAoHUmVxdWVzdBIXCg9zdGFydF9ibG9ja19udW0YASABKAMSFAoMc3RhcnRfY3Vyc29yGAIgASgJEhYKDnN0b3BfYmxvY2tfbnVtGAMgASgEEhkKEWZpbmFsX2Jsb2Nrc19vbmx5GAQgASgIEhcKD3Byb2R1Y3Rpb25fbW9kZRgFIAEoCBIVCg1vdXRwdXRfbW9kdWxlGAYgASgJEioKB3BhY2thZ2UYByABKAsyGS5zZi5zdWJzdHJlYW1zLnYxLlBhY2thZ2USOQoGcGFyYW1zGAggAygLMikuc2Yuc3Vic3RyZWFtcy5ycGMudjMuUmVxdWVzdC5QYXJhbXNFbnRyeRIPCgduZXR3b3JrGAkgASgJEjAKKGRlYnVnX2luaXRpYWxfc3RvcmVfc25hcHNob3RfZm9yX21vZHVsZXMYCiADKAkSEQoJbm9vcF9tb2RlGAsgASgIEh4KFmxpbWl0X3Byb2Nlc3NlZF9ibG9ja3MYDCABKAQSGgoSZGV2X291dHB1dF9tb2R1bGVzGA0gAygJEiUKHXByb2dyZXNzX21lc3NhZ2VzX2ludGVydmFsX21zGA4gASgEEhYKDnBhcnRpYWxfYmxvY2tzGBAgASgIGi0KC1BhcmFtc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAFKBAgPEBAyUwoGU3RyZWFtEkkKBkJsb2NrcxIdLnNmLnN1YnN0cmVhbXMucnBjLnYzLlJlcXVlc3QaHi5zZi5zdWJzdHJlYW1zLnJwYy52Mi5SZXNwb25zZTABQk9aTWdpdGh1Yi5jb20vc3RyZWFtaW5nZmFzdC9zdWJzdHJlYW1zL3BiL3NmL3N1YnN0cmVhbXMvcnBjL3YzO3Bic3Vic3RyZWFtc3JwY3YzYgZwcm90bzM", [file_google_protobuf_any, file_sf_firehose_v2_firehose, file_sf_substreams_rpc_v2_service, file_sf_substreams_v1_clock, file_sf_substreams_v1_modules, file_sf_substreams_v1_package]);

/**
 * @generated from message sf.substreams.rpc.v3.Request
 */
export type Request = Message<"sf.substreams.rpc.v3.Request"> & {
  /**
   * if positive, determines the absolute requested start block
   * if 0, the start block is determined by the chain's first streamable block
   * if negative, the start block is relative to the chain HEAD (determined server-side at the time of the request)
   *
   * @generated from field: int64 start_block_num = 1;
   */
  startBlockNum: bigint;

  /**
   * start_cursor has precedence over start_block_num
   *
   * @generated from field: string start_cursor = 2;
   */
  startCursor: string;

  /**
   * if non-zero, processing will stop *before* this block (exclusive)
   * if zero, processing will continue and keep up with the chain HEAD
   *
   * @generated from field: uint64 stop_block_num = 3;
   */
  stopBlockNum: bigint;

  /**
   * With final_block_only, you only receive blocks that are irreversible:
   * 'final_block_height' will be equal to current block and no 'undo_signal' will ever be sent
   *
   * @generated from field: bool final_blocks_only = 4;
   */
  finalBlocksOnly: boolean;

  /**
   * Substreams has two mode when executing your module(s) either development mode or production
   * mode. Development and production modes impact the execution of Substreams, important aspects
   * of execution include:
   * * The time required to reach the first byte.
   * * The speed that large ranges get executed.
   * * The module logs and outputs sent back to the client.
   *
   * By default, the engine runs in developer mode, with richer and deeper output. Differences
   * between production and development modes include:
   * * Forward parallel execution is enabled in production mode and disabled in development mode
   * * The time required to reach the first byte in development mode is faster than in production mode.
   *
   * Specific attributes of development mode include:
   * * The client will receive all of the executed module's logs.
   * * It's possible to request specific store snapshots in the execution tree (via `debug_initial_store_snapshot_for_modules`).
   * * Multiple module's output is possible.
   *
   * With production mode`, however, you trade off functionality for high speed enabling forward
   * parallel execution of module ahead of time.
   *
   * @generated from field: bool production_mode = 5;
   */
  productionMode: boolean;

  /**
   * @generated from field: string output_module = 6;
   */
  outputModule: string;

  /**
   * whole spkg package
   *
   * @generated from field: sf.substreams.v1.Package package = 7;
   */
  package?: Package;

  /**
   * params applied over the package
   *
   * @generated from field: map<string, string> params = 8;
   */
  params: { [key: string]: string };

  /**
   * network choice applied over the package
   *
   * @generated from field: string network = 9;
   */
  network: string;

  /**
   * Available only in developer mode
   *
   * @generated from field: repeated string debug_initial_store_snapshot_for_modules = 10;
   */
  debugInitialStoreSnapshotForModules: string[];

  /**
   * Prepares the stores and caches on the server, sending only progress messages and "minimal" clock data (and cursor)
   *
   * @generated from field: bool noop_mode = 11;
   */
  noopMode: boolean;

  /**
   * If set, the engine will reject a request if the number of blocks to process (including preparing the stores) is above this limit.
   * Useful as a safeguard for managing costs
   *
   * @generated from field: uint64 limit_processed_blocks = 12;
   */
  limitProcessedBlocks: bigint;

  /**
   * Available only in developer mode
   * If set, the server will only send the output of these modules.
   * If unset, all the outputs are sent.
   * This allows the user to reduce the payload in dev mode, while still getting some extra debugging information
   *
   * @generated from field: repeated string dev_output_modules = 13;
   */
  devOutputModules: string[];

  /**
   * Progress_messages_interval_ms is the interval between progress messages, in milliseconds (min 500ms)
   * default: start at 500ms and ramp up to 5000ms within 1min
   *
   * @generated from field: uint64 progress_messages_interval_ms = 14;
   */
  progressMessagesIntervalMs: bigint;

  /**
   * If true, blocks close to head will be sent in "partials" as soon as we get them.
   * This means that you will get different versions of the same block number, each an incomplete increment
   * Other blocks will be sent completely (older blocks, or blocks for which the provider did not get a partial in time)
   *
   * @generated from field: bool partial_blocks = 16;
   */
  partialBlocks: boolean;
};

/**
 * Describes the message sf.substreams.rpc.v3.Request.
 * Use `create(RequestSchema)` to create a new message.
 */
export const RequestSchema: GenMessage<Request> = /*@__PURE__*/
  messageDesc(file_sf_substreams_rpc_v3_service, 0);

/**
 * @generated from service sf.substreams.rpc.v3.Stream
 */
export const Stream: GenService<{
  /**
   * Request processing of blocks via substreams engine.
   * Similar to `sf.substreams.rpc.v2.Stream/Blocks` request, but:
   *   - the full spkg package is sent instead of just the modules
   *   - 'params' and 'network' fields are sent to apply the user-defined params to the package server-side
   * Responses are identical to those of the v2 request.
   *
   * @generated from rpc sf.substreams.rpc.v3.Stream.Blocks
   */
  blocks: {
    methodKind: "server_streaming";
    input: typeof RequestSchema;
    output: typeof ResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_sf_substreams_rpc_v3_service, 0);

